name: Deno CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@master
      with:
        deno-version: 0.x
    - run: deno test --allow-read carrot/tests/test-*.ts
