name: Deno CI

on:
  push:
    branches: [ tests ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@master
      with:
        deno-version: v1.x
    - name: Run tests
      run: deno test --allow-read --filter 1305 carrot/tests/test-perf.ts
